# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoreleaserLive < Formula
  desc "GoReleaser on #DevOpsLiveCZ"
  homepage "https://github.com/vojtechmares/goreleaser-live"
  version "1.2.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/vojtechmares/goreleaser-live/releases/download/v1.2.0/goreleaser-live_1.2.0_macOS_x86_64.tar.gz"
    sha256 "95219d50491a8a923eaac5ab937dd10b405c0c68abf2acebd1fa67d9c4b6d0cd"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/vojtechmares/goreleaser-live/releases/download/v1.2.0/goreleaser-live_1.2.0_macOS_arm64.tar.gz"
    sha256 "1d07bb53c33b7265f69fd34bae9b33a6b78b08c202ae8a12ace37f6bf225f3b5"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/vojtechmares/goreleaser-live/releases/download/v1.2.0/goreleaser-live_1.2.0_Linux_x86_64.tar.gz"
    sha256 "dc6bf1b3d94da51c169520ab296214087d3cf6ead70fe6211756574db7eaa7eb"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/vojtechmares/goreleaser-live/releases/download/v1.2.0/goreleaser-live_1.2.0_Linux_arm64.tar.gz"
    sha256 "46c3dfe4c382a658b34896cf0460dcb8e639f9994527c17927ebaaa73a75e1bb"
  end

  def install
    bin.install "goreleaser-live"
  end

  def caveats; <<~EOS
    GoReleaser example, source: https://github.com/vojtechmares/goreleaser-live
  EOS
  end

  test do
    system "#{bin}/goreleaser-live"
  end
end
