# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoreleaserLive < Formula
  desc "GoReleaser on #DevOpsLiveCZ"
  homepage "https://github.com/vojtechmares/goreleaser-live"
  version "1.3.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/vojtechmares/goreleaser-live/releases/download/v1.3.0/goreleaser-live_1.3.0_macOS_x86_64.tar.gz"
    sha256 "f7deb4e87cdc88014715d8ecce394ce56c37e09b5ac68ca1a1af3fcfa049a032"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/vojtechmares/goreleaser-live/releases/download/v1.3.0/goreleaser-live_1.3.0_macOS_arm64.tar.gz"
    sha256 "87365dfbc668cce6715ac7066baab20e62f32bb465e5f8853fdde1ddff09f8a9"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/vojtechmares/goreleaser-live/releases/download/v1.3.0/goreleaser-live_1.3.0_Linux_x86_64.tar.gz"
    sha256 "f51f785be668bbc891d1e3177eef19ec6132dee52765a3478db5059eca50fb1e"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/vojtechmares/goreleaser-live/releases/download/v1.3.0/goreleaser-live_1.3.0_Linux_arm64.tar.gz"
    sha256 "850421eca1c92b5d3bd15472383782949c632d912371dcbf60a309302c706eb2"
  end

  def install
    bin.install "goreleaser-live"
  end

  def caveats; <<~EOS
    GoReleaser example, source: https://github.com/vojtechmares/goreleaser-live
  EOS
  end

  test do
    system "#{bin}/goreleaser-live"
  end
end
